### PR TITLE
16 add passwords to player

### PR DESCRIPTION
**Pull request by 1337807**
FINISHED SHIP IT

BEST CODEZ EVAR

(work in progress)
:warning: DO NOT MERGE :warning:

### CODE REVIEW

**Comment by tkrajcar** [comment]
@1337807 JSYK, I did some crazygonuts refactoring and things are about a million times more sane now (see https://github.com/tkrajcar/carbonmu/commit/20e9b6e4a2528dd5decce574894322a401ec8567 and https://github.com/tkrajcar/carbonmu/commit/c68b78943502eac557155fe6f6a789c87d6f15df), unfortunately this won't merge any more since the underlying file moved to `lib/carbonmu/game_objects/player.rb`. Happy to leave this open if you want to keep haxoring on it. Also happy to pair on it sometime.

**Comment by 1337807** [comment]
I do! We’ll fix up our ugly pull request in our next pairing session, sorry it’s been left to rot.

**Comment by tkrajcar** [comment]
Cool! I would love to join you guys and be able to answer questions about things too.

**Comment by 1337807** [comment]
FINE I'M NEVER HELPING AGAIN!

**Pull request closed without merging**
