### PR TITLE
Test on 2.3

### PR DESCRIPTION
**Pull request by nateberkopec**
Cause why not. We'll see if this Just Works (TM).

### CODE REVIEW

**Comment by tkrajcar** [comment]
Haha, thanks! I also intend to add an allow_fail'd ruby-head at some point. Will merge on :green_apple:.

(Let me know if you actually want to do anything with this project; it's unfortunately far from non-me-user ready...)

**Comment by nateberkopec** [comment]
The load paths aren't quite working for me. `bin/carbonmu` doesn't work, and neither does `rake console`. Amidoinrite?

```
nodachi:carbonmu nateberkopec$ bin/carbonmu start
/Users/nateberkopec/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- carbonmu (LoadError)
	from /Users/nateberkopec/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from bin/carbonmu:3:in `<main>'
```

**Comment by tkrajcar** [comment]
Can confirm the `bin/carbonmu start` doesn't work for me either - try `bundle exec carbonmu start`. The `rake console` does work, though; can you paste the output if it's different than your bin output?

**Comment by nateberkopec** [comment]
Ohhh, bundle exec fixes it for both. Why does that work? Is that because the gemspec is executed?

**Comment by nateberkopec** [comment]
Also RE: this PR, I have no idea why that doesn't work. In raven-ruby we can test Ruby 2.3 by specifying `ruby-2.3.0` as the version is that OK?

**Comment by tkrajcar** [comment]
Sure, that's fine! And I just pushed 209ec8c2e280fcb42a600ecb9ca634991377e9e6 which corrects the bin script and Rakefile when run w/o bundle exec.

**Pull request merged**
